# This is a basic workflow to help you get started with Actions

name: Push frontend build output to the backend repository

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Navigate to app
        run: cd ./kachow-app/
        
      - name: Run yarn
        run: yarn install && yarn build

      - name: Navigate back
        run: cd ..
        
      - name: Push to backend repository
        uses: XenonMolecule/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './kachow-app/build'
          destination-github-username: 'XenonMolecule'
          destination-repository-name: 'Kachow-Backend'
          user-email: michael_ryan_2000@yahoo.com
          target-branch: main
          target-directory: build
